version: pre-0.0.1#{build}
configuration: Release
build:
  project: OpenMC2.sln
  verbosity: minimal
after_build:
- cmd: 7z a OpenMC2.zip .\Release\OpenMC2.exe .\Release\OpenMC2.dll .\Release\binkwSB.dll .\Release\mssSB.dll
artifacts:
- path: OpenMC2.zip
  name: zip-archive
deploy:
- provider: GitHub
  auth_token:
    secure: cq8ZIAEaUXspagwOEFf81K6+vIjvhsX2d4u5/7egRGwSvlPyrkrv42FY+hRlF9sX
  artifact: zip-archive
  on:
    appveyor_repo_tag: true